version: '3.5'
services:
  fiap-microservices:
    # build:
    #   context:  services/java-user-api/
    #   dockerfile: Dockerfile
    image: wellbastos/fiap-microservices:latest 
    container_name: fiap-microservices
    ports:
    - "8080:8080"
    - "7001:7000"
    environment:
      PORT: 8080
      ENV: docker
      JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:7000
    networks:
    - fiap-microservices
  # consumer-php-app:
  #   build:
  #     context: services/php-slack-consumer/
  #     dockerfile: Dockerfile
  #   image: laravel
  #   container_name: consumer-php-app
  #   working_dir: /var/www
  #   volumes:
  #     - ./services/php-slack-consumer:/var/www
  #   networks:
  #   - fiap-microservices
  db:
    image: mysql:5.7
    volumes:
    - db-data:/var/lib/mysql/
    container_name: fiap-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: microservices
    ports:
    - "3306:3306"
    networks:
    - fiap-microservices
  postgres:
    image: postgres:9.5-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=notification
    ports:
     - "5432:5432"
    networks:
    - fiap-microservices
  rabbitmq:
    image: rabbitmq:3-management
    container_name: fiap-rabbit
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
      - RABBITMQ_DEFAULT_VHOST=/
    ports:
    - "15672:15672"
    - "5672:5672"
    - "25676:25676"
    networks:
    - fiap-microservices


  frontend:
    image: wellbastos/frontend:latest
    container_name: fiap-front
    restart: always
    ports:
      - 8081:8080
    networks:
    - fiap-microservices



networks:
  fiap-microservices:
    # name: fiap-microservices
volumes:
  db-data:
